 [theme]
base="light"
primaryColor="#A3B18A"            # Vert amande doux
backgroundColor="#F5F1E7"          # Beige crème très clair
secondaryBackgroundColor="#E8E1D9" # Praliné léger
textColor="#4B4637"                # Brun taupe pour un texte chaleureux
font="serif"


[server]
headless = true

[browser]
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false

[client]
toolbarMode = "minimal"
