 [theme]
primaryColor = "#A26769"               # rose vieux/terre cuite
backgroundColor = "#FFF8F0"            # crème
secondaryBackgroundColor = "#F3E9DC"   # beige rosé
textColor = "#3B3B3B"                  # anthracite doux
font = "sans serif"


[server]
headless = true

[browser]
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false

[client]
toolbarMode = "minimal"
